#!/usr/bin/env perl

use strict;
use warnings;
use local::lib './local';
use lib 'lib';

use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('BlogVillain');
