=encoding utf8
=pod

=head1 Deploy

 $ ./set_env

 $ source /path/.profile

 $ carton install cp

 $ perl deploy.pl

=head1 Tasks

 # pod2html
 sqlite -> pod -> html

 # html2pod
 html -> pod -> sqlite

 # validating pod

 # watching pod files
 programs/watch-pod

 # OAuth

 # scripts for deploy
 set_env -> source -> cpanfile -> deploy.pl

=head1 TODO

 react

 Add new =code paragraph for pod and vim syntax

=cut
