#!/usr/bin/env bash

# Set BLOGVILLAIN_HOME
PROFILE="$HOME/.profile";

source "$PROFILE";

if [ -z "$BLOGVILLAIN_HOME" ]; then
	echo "\$BLOGVILLAIN_HOME Does not exist"
	echo "" >> $PROFILE
	echo "" >> $PROFILE
	echo "# set ENV for BlogVillain" >> $PROFILE
	echo "export BLOGVILLAIN_HOME=$HOME/blog_villain" >> $PROFILE
fi

source "$PROFILE";

if [ -z "$PERL5LIB" ]; then
	echo "export PERL5LIB=\$BLOGVILLAIN_HOME/local/lib/perl5:\$PERL5LIB" >> $PROFILE
fi

echo ""
echo ""
echo "======== type 'source $PROFILE'!!!!! ========"
echo ""
echo ""
