=encoding utf8
=pod

=head1 NAME

pipe And fork

=head1 SYNOPSIS

=begin html

<pre><code class="perl">
 #!/usr/bin/env perl
 
 use strict;
 use warnings;
 use feature qw/ say /;
 
 use IO::Handle;
 
 my ($reader, $writer);
 pipe ( $reader, $writer );
 $writer->autoflush(1);
 
 if ( my $pid = fork ) { # write to child
     close $reader;
     say $writer "Parent pid $$ is sending this\n";
     close $writer;
     waitpid($pid, 0);
 }
 else { # read from parent
     die "cannot fork: $!" unless defined $pid;
     close $writer;
     chomp( my $line = <$reader>);
     say "Child pid $$ just read this: '$line'\n";
     close $reader;
     exit;
 }
</code></pre>

=end html

=head1 DESCRIPTION

=begin html

<pre><code class="perl">
 pipe ( $reader, $writer );
</code></pre>

=end html

open READHANDLE and WRITEHANDLE.

In parent, I<$reader> for child, is closed. 
Write string to child, and wait for exit signal from child

In child, I<$writer> for parent, is closed.
Read string from parent, and terminated.

=cut

